In [20]:
import tensorflow as tf
tf.enable_eager_execution()
temp=tf.math.log([[2.,10.],[10,2]])

In [21]:
print(temp)

tf.Tensor(
[[0.6931472 2.3025851]
 [2.3025851 0.6931472]], shape=(2, 2), dtype=float32)


In [36]:
temp_2=tf.random.categorical(temp, 20)
temp_2

<tf.Tensor: id=93, shape=(2, 20), dtype=int64, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1]],
      dtype=int64)>

In [45]:
a=tf.constant([[[3,3],[5,7]],[[1,2],[6,5]]])
b=tf.constant([[[3]]])
c=tf.multiply(a,b)
print(c)
print(b)

tf.Tensor(
[[[ 9  9]
  [15 21]]

 [[ 3  6]
  [18 15]]], shape=(2, 2, 2), dtype=int32)
tf.Tensor([[[3]]], shape=(1, 1, 1), dtype=int32)
